### ISSUE TITLE
Mailcatcher could not be found and loaded 

### ISSUE THREAD

**Issue by jackmolnar** [captbaritone/codeception-mailcatcher-module#18]
I can't seem to figure out why this won't load. I had the module installed and it was working fine recently, now it won't load.

I can bring up MailCatcher in my browser, the url and port are correct in the yml file.

Did something change?

```
class_name: FunctionalTester
modules:
    enabled: [Filesystem, FunctionalHelper, Laravel4, MailCatcher]
    config:
        MailCatcher:
            url: 'http://localhost'
            port: '1080'
```

**Comment by captbaritone** [comment]
Everything seems to be working fine here.

Could you include your `composer.json` file as well as a dump of the output you're getting when you run Codeception?

**Comment by yearofthegus** [comment]
I'm running into this issue as well.

**composer.json**
```json
{
    "name": "symfony/framework-standard-edition",
    "license": "MIT",
    "type": "project",
    "description": "The \"Symfony Standard Edition\" distribution",
    "autoload": {
        "psr-0": { "": "src/", "SymfonyStandard": "app/" }
    },
    "require": {
        "php": ">=5.3.3",
        "symfony/symfony": "2.6.*",
        "doctrine/orm": "~2.2,>=2.2.3",
        "doctrine/doctrine-bundle": "~1.2",
        "doctrine/doctrine-fixtures-bundle": "2.2.*",
        "twig/extensions": "~1.0",
        "symfony/assetic-bundle": "~2.3",
        "symfony/swiftmailer-bundle": "~2.3",
        "symfony/monolog-bundle": "~2.4",
        "sensio/distribution-bundle": "~3.0",
        "sensio/framework-extra-bundle": "~3.0",
        "incenteev/composer-parameter-handler": "~2.0",
        "liip/imagine-bundle": "dev-master",
        "friendsofsymfony/jsrouting-bundle": "1.*@dev",
        "friendsofsymfony/elastica-bundle": "3.0.*",
        "white-october/pagerfanta-bundle": "~1.0",
        "gregwar/captcha-bundle": "dev-master",
        "snc/redis-bundle": "1.1.*",
      "excelwebzone/recaptcha-bundle": "~1.2",
      "predis/predis": "0.8.*"
    },
    "require-dev": {
        "sensio/generator-bundle": "~2.3",
        "liip/functional-test-bundle": "~1.0",
        "codeception/codeception": "~2.0",
        "captbaritone/mailcatcher-codeception-module": "1.*"
    },
    "scripts": {
        "post-root-package-install": [
            "SymfonyStandard\\Composer::hookRootPackageInstall"
        ],
        "post-install-cmd": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::removeSymfonyStandardFiles"
        ],
        "post-update-cmd": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::removeSymfonyStandardFiles"
        ]
    },
    "config": {
        "bin-dir": "bin"
    },
    "extra": {
        "symfony-app-dir": "app",
        "symfony-web-dir": "web",
        "incenteev-parameters": {
            "file": "app/config/parameters.yml"
        },
        "branch-alias": {
            "dev-master": "2.6-dev"
        }
    }
}
```

**acceptance tester config**
```yaml
class_name: AcceptanceTester
modules:
    enabled:
        - WebDriver
        - AcceptanceHelper
        - Db
        - Cli
        - Memcache
        - Asserts
        - MailCatcher
    config:
        WebDriver:
            url: 'http://localhost/'
            browser: firefox
            window_size: 1024x768
            wait: 0
            capabilities:
                unexpectedAlertBehavior: 'accept'
        Db:
            dsn: 'mysql:host=localhost;dbname=test'
            user: 'testing'
            password: secret
            dump: 'tests/_data/dump.sql'
            populate: true
            cleanup: true
        Memcache:
            host: localhost
            port: 11211
        MailCatcher:
            url: http://localhost
            port: 1080
```

**Console output**
```
$ codecept build
Building Actor classes for suites: acceptance, unit, functional


                                             
  [Codeception\Exception\Configuration]      
  MailCatcher could not be found and loaded  
                                             


build [-c|--config[="..."]]
```
