### ISSUE TITLE
  MailCatcher could not be found and loaded

### ISSUE THREAD

**Issue by siegerhansma** [captbaritone/codeception-mailcatcher-module#3]
On running codecept.phar build I get the following error: 
  MailCatcher could not be found and loaded

Not sure what I'm doing wrong. Any ideas?

acceptance.suite.yml looks like this 

```
# Codeception Test Suite Configuration

# suite for acceptance tests.
# perform tests in browser using the WebDriver or PhpBrowser.
# If you need both WebDriver and PHPBrowser tests - create a separate suite.

class_name: AcceptanceTester
modules:
    enabled:
        - PhpBrowser
        - AcceptanceHelper
        - MailCatcher
    config:
        PhpBrowser:
            url: 'http://afspraaq.dev'
        MailCatcher:
            url: 'http://localhost'
            port: '1080'

```
