### ISSUE TITLE
ConnectException

### ISSUE THREAD

**Issue by noloop** [captbaritone/codeception-mailcatcher-module#47]
I'm getting a cURL error that can not connect. Am I forgetting to set something up?

`  [GuzzleHttp\Exception\ConnectException] cURL error 7: Failed to connect to 127.0.0.1 port 1080: Connection refused (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)  `

I've tried to change the door, and it still does not work.

my **_api.suite.yml_**:

```
actor: ApiTester
modules:
    enabled:
        - REST:
            url: http://localhost:3000/my-project/api
            depends: PhpBrowser
            part: Json
        - MailCatcher:
            url: 'http://127.0.0.1'
            port: '1080'
```
